// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutMe: typeof import('./components/aboutMe.vue')['default']
    ArCard: typeof import('./components/arCard.vue')['default']
    ArticleDir: typeof import('./components/articleDir.vue')['default']
    ArticleList: typeof import('./components/articleList.vue')['default']
    BigCard: typeof import('./components/bigCard.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IconsFriend: typeof import('./components/iconsFriend.vue')['default']
    LongArList: typeof import('./components/longArList.vue')['default']
    MidCard: typeof import('./components/midCard.vue')['default']
    MiniCard: typeof import('./components/miniCard.vue')['default']
    Radar: typeof import('./components/radar.vue')['default']
    RightNav: typeof import('./components/rightNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallArCard: typeof import('./components/smallArCard.vue')['default']
    SmallCard: typeof import('./components/smallCard.vue')['default']
    Waves: typeof import('./components/waves.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
